# Generated by Django 5.0.3 on 2024-04-08 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hist',
            old_name='ai',
            new_name='label',
        ),
        migrations.RenameField(
            model_name='hist',
            old_name='hu',
            new_name='prob',
        ),
    ]
